In [1]:
import numpy as np
from boxvectors import directions as directions
import Initial_Parameters as ip
from md import System
from md import md
from distribution import maxwellboltzmann
import matplotlib.pyplot as plt
from scipy.special import erf
from scipy.special import erfc
from scipy.constants import epsilon_0
%matplotlib inline

In [2]:
Symbols = ip.Symbols
Coefficients = ip.Coefficients
Charges = ip.Charges
N = ip.N*np.sum(Coefficients)
L = ip.L
T = ip.T
dt = ip.dt
p_rea = ip.p_rea
std = ip.std
n_boxes_short_range = ip.n_boxes_short_range
p_error = ip.p_error
Sys= System(Symbols, Coefficients, Charges, N/2)
Labels = Sys.get_Labels()
Sigma, Epsilon = Sys.get_LJ_parameter()
r_cut_coulomb = ip.r_cut_coulomb
r_cut_LJ = ip.r_cut_LJ
r_switch = ip.r_switch
switch_parameter = ip.switch_parameter
m = Labels[:,0]

In [3]:
d = 1e-9
L*= d
r_cut_LJ *= d
r_cut_coulomb *= d

In [4]:
L

array([  1.00000000e-10,   1.00000000e-10,   1.00000000e-10])

In [5]:
def get_random_starting_Positions(N,L):
    Positions = np.zeros((N,3))
    Positions[:,0] = np.linspace(0,L[0],N, endpoint = False)
    Positions[:,1] = np.linspace(0,L[1],N, endpoint = False)
    Positions[:,2] = np.linspace(0,L[2],N, endpoint = False)
    np.random.shuffle(Positions[:,0])
    np.random.shuffle(Positions[:,1])
    np.random.shuffle(Positions[:,2])
    return Positions
Positions = get_random_starting_Positions(N,L)
Velocities = maxwellboltzmann().sample_distribution(N,m,T)
Forces = np.zeros((N,3))
R = np.linalg.norm(Positions,axis=1)

In [6]:
r_cut_LJ

7.000000000000002e-11

In [7]:
MD = md(
    Positions, 
    R, 
    Labels, 
    Velocities,
    Forces, 
    L, 
    T, 
    Sigma, 
    Epsilon, 
    switch_parameter,
    r_switch,
    r_cut_LJ,
    dt, 
    std,
    n_boxes_short_range,
    p_rea,
    p_error,
    Symbols)

In [8]:
MD.forces = MD.get_forces()

In [9]:
print MD.get_energy()
print MD.get_potential()
print MD.forces


6.01343888638
[  8.71823354e+18   8.30108529e+19   2.33959176e+20   2.79358390e+21
   1.59204154e+21   6.73026300e+18   8.63561653e+21   7.82847034e+18
   6.30666331e+19   5.22908263e+19   4.97396438e+25   1.41187309e+21
   4.82495363e+21   4.97407696e+25   1.14567981e+22   8.51166046e+21
   1.02760401e+22   4.81424005e+20   1.30999168e+24   1.31840856e+24]
[[ -3.42925994e+22  -4.47176733e+22  -7.68631948e+20]
 [ -7.53938623e+21  -8.25608308e+21  -1.66319561e+22]
 [ -3.46100836e+24  -1.04021706e+25  -3.46872829e+24]
 [ -8.71431742e+21  -4.23306487e+21  -1.85567301e+22]
 [ -1.72649943e+27  -8.63251306e+26  -8.11668373e+20]
 [ -1.97382681e+24  -7.21644282e+23  -1.36279619e+24]
 [ -1.88198019e+22  -3.74956187e+22  -7.49719016e+22]
 [ -1.61300381e+24  -1.35941397e+21  -1.07571433e+24]
 [ -7.62973241e+22  -2.38654690e+22  -3.91008469e+22]
 [ -2.82360549e+25  -1.41528605e+25  -2.82182381e+25]
 [ -2.35332827e+25  -3.52911654e+25  -1.17719297e+25]
 [ -2.82851724e+25  -1.81654663e+25  -3.601248

In [10]:
import os
cwd = os.getcwd()
cwd

'C:\\Users\\Marco\\Documents\\GitHub\\compsci-proj-md-OptimalCutoff\\md'

In [11]:
MD.get_traj(N_steps = 20, Energy_threshold=1e-20, Energy_save=1, Temperature_save=1, Frame_save=1, path=cwd)

100.0% of steps \completed

'Maximum Number of Steps reached, system eventually not converged'