In [20]:
import numpy as np

#creates a dummy array -> 3D matrix has similiar handling like trajectory
array=np.zeros((3,2,2))
array[1,:,:]=np.ones((2,2))
array[2,:,:]=2*np.ones((2,2))


#iterates through a frame and writes the frame to a file
for arriteration in range(array.shape[0]):
    #opens a file called filename.txt with append-mode
    #if the file does not exist, then it will be created automatically
    file = open('filename.txt','a')
    #appends the frame to the last position of the file
    file.write(str(array[arriteration,:,:]) + "\n")
    #closes the file to demonstrate, that the write method appends the frame and do not overwrite
    file.close()


[[ 2.  2.]
 [ 2.  2.]]
[[ 2.  2.]
 [ 2.  2.]]
[[ 2.  2.]
 [ 2.  2.]]
